// editor/src/components/dialogs/SavePresetDialog.vue
<script setup lang="ts">
// ---------- Save-preset dialog ----------
import { ref } from 'vue'
import { useI18n } from '../../i18n.ts'
import { presetFromSettings } from '../../composables/useSettings.ts'
import { upsertPreset } from '../../composables/usePresets.ts'
import { useApp } from '../../composables/useApp.ts'
import { toast } from '../../composables/useToasts.ts'
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from '../ui/dialog'
import { Button } from '../ui/button'
import { Label } from '../ui/label'
import { Input } from '../ui/input'

const { t } = useI18n()
const { closeModal } = useApp()

const name = ref('')

function save(): void {
  const trimmed = name.value.trim()
  if (!trimmed) {
    toast(t('modal.savePreset.emptyName'), 'warn')
    return
  }
  upsertPreset(presetFromSettings(trimmed))
  toast(t('modal.savePreset.saved', { name: trimmed }))
  closeModal()
}
</script>

<template>
  <Dialog :open="true" @update:open="(o) => !o && closeModal()">
    <DialogContent class="sm:max-w-md">
      <DialogHeader>
        <DialogTitle>{{ t('modal.savePreset.title') }}</DialogTitle>
        <DialogDescription>{{ t('modal.savePreset.hint') }}</DialogDescription>
      </DialogHeader>
      <div class="space-y-2">
        <Label for="preset-name" class="text-xs text-muted-foreground">{{ t('modal.savePreset.name') }}</Label>
        <Input
          id="preset-name"
          :model-value="name"
          :placeholder="t('modal.savePreset.placeholder')"
          class="w-full"
          @update:model-value="name = String($event)"
          @keydown.enter="save"
        />
      </div>
      <DialogFooter>
        <Button variant="outline" @click="closeModal">{{ t('modal.close') }}</Button>
        <Button id="do-save" @click="save">{{ t('modal.savePreset.do') }}</Button>
      </DialogFooter>
    </DialogContent>
  </Dialog>
</template>

// editor/src/components/dialogs/SavePresetDialog.tsx
// ---------- Save-preset dialog ----------
import { useState } from 'react'
import { useI18n } from '@/i18n.ts'
import { useSettingsStore, presetFromSettings } from '@/stores/settings.ts'
import { usePresetsStore } from '@/stores/presets.ts'
import { useAppStore } from '@/stores/app.ts'
import { toast } from '@/composables/useToasts.ts'
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from '@opengptdetect/ui'
import { Button } from '@opengptdetect/ui'
import { Label } from '@opengptdetect/ui'
import { Input } from '@opengptdetect/ui'

export function SavePresetDialog() {
  const { t } = useI18n()
  const closeModal = useAppStore((s) => s.closeModal)
  const [name, setName] = useState('')

  function save(): void {
    const trimmed = name.trim()
    if (!trimmed) {
      toast(t('modal.savePreset.emptyName'), 'warn')
      return
    }
    const settings = useSettingsStore.getState().settings
    usePresetsStore.getState().upsertPreset(presetFromSettings(settings, trimmed))
    toast(t('modal.savePreset.saved', { name: trimmed }))
    closeModal()
  }

  return (
    <Dialog open onOpenChange={(o) => !o && closeModal()}>
      <DialogContent className="sm:max-w-md">
        <DialogHeader>
          <DialogTitle>{t('modal.savePreset.title')}</DialogTitle>
          <DialogDescription>{t('modal.savePreset.hint')}</DialogDescription>
        </DialogHeader>
        <div className="space-y-2">
          <Label htmlFor="preset-name" className="text-xs text-muted-foreground">{t('modal.savePreset.name')}</Label>
          <Input
            id="preset-name"
            value={name}
            placeholder={t('modal.savePreset.placeholder')}
            className="w-full"
            onChange={(e) => setName(e.target.value)}
            onKeyDown={(e) => e.key === 'Enter' && save()}
          />
        </div>
        <DialogFooter>
          <Button variant="outline" onClick={closeModal}>{t('modal.close')}</Button>
          <Button id="do-save" onClick={save}>{t('modal.savePreset.do')}</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}
