// editor/src/components/dialogs/SettingsDialog.tsx
// ---------- Settings dialog ----------
// Organized into sections; every field is one row in the DECLARATIVE `fields`
// array below (a future setting = one more row, no ad-hoc markup). Each row
// knows how to render its control and which settings key it mutates. Committing
// goes through `patchSettings`; the app store's settings subscription then
// fires the matching refresh (editor decoration / fonts / health probe), so no
// per-field commit hook is needed anymore.
import { useI18n, type MessageKey } from '@/i18n.ts'
import { useSettingsStore } from '@/stores/settings.ts'
import { useAppStore } from '@/stores/app.ts'
import { clamp } from '@/util.ts'
import type { HeatStyle } from '@/types.ts'
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from '@/components/ui/dialog'
import { Button } from '@/components/ui/button'
import { Label } from '@/components/ui/label'
import { Input } from '@/components/ui/input'
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select'
import { Slider } from '@/components/ui/slider'
import { Separator } from '@/components/ui/separator'
import { ColorStopsEditor } from '@/components/ui/ColorStopsEditor'

type Field =
  | { kind: 'text'; key: 'serverUrl' | 'fontFamily'; labelKey: MessageKey; listId?: string }
  | { kind: 'select'; key: 'style'; labelKey: MessageKey; options: Array<{ value: HeatStyle; labelKey: MessageKey }> }
  | { kind: 'slider'; key: 'opacity'; labelKey: MessageKey }
  | { kind: 'number'; key: 'fontSize'; labelKey: MessageKey; min: number; max: number }

const fields: Field[] = [
  { kind: 'text', key: 'serverUrl', labelKey: 'modal.settings.backendUrl' },
  {
    kind: 'select', key: 'style', labelKey: 'modal.settings.style',
    options: [
      { value: 'background', labelKey: 'modal.settings.styleBackground' },
      { value: 'underline', labelKey: 'modal.settings.styleUnderline' },
      { value: 'both', labelKey: 'modal.settings.styleBoth' }
    ]
  },
  { kind: 'slider', key: 'opacity', labelKey: 'modal.settings.opacity' },
  { kind: 'number', key: 'fontSize', labelKey: 'modal.settings.fontSize', min: 10, max: 32 },
  { kind: 'text', key: 'fontFamily', labelKey: 'modal.settings.fontFamily', listId: 'font-list' }
]

const FONT_CHOICES = [
  "'Segoe UI', 'Microsoft YaHei', system-ui, sans-serif",
  "'Microsoft YaHei', sans-serif",
  'SimSun, serif',
  'KaiTi, serif',
  "Consolas, 'Courier New', monospace",
  'Georgia, serif'
]

export function SettingsDialog() {
  const { t } = useI18n()
  const settings = useSettingsStore((s) => s.settings)
  const closeModal = useAppStore((s) => s.closeModal)
  const patch = useSettingsStore((s) => s.patchSettings)

  const opacityPct = `${Math.round(settings.opacity * 100)}%`

  function onSelectChange(field: Field, value: string): void {
    if (field.kind === 'select') patch({ style: value as HeatStyle })
  }

  function onOpacityChange(value: number[] | undefined): void {
    patch({ opacity: clamp(value?.[0] ?? settings.opacity, 0.05, 1) })
  }

  function onNumberChange(field: Field & { kind: 'number' }, value: string): void {
    patch({ [field.key]: clamp(Number(value) || 16, field.min, field.max) })
  }

  function onTextChange(field: Field & { kind: 'text' }, value: string): void {
    const v = value.trim()
    if (!v) return
    patch({ [field.key]: v })
  }

  function resetStops(): void {
    useSettingsStore.getState().resetStops()
  }

  return (
    <Dialog open onOpenChange={(o) => !o && closeModal()}>
      <DialogContent className="sm:max-w-2xl">
        <DialogHeader>
          <DialogTitle>{t('modal.settings.title')}</DialogTitle>
          <DialogDescription>{t('modal.settings.hint')}</DialogDescription>
        </DialogHeader>

        <div className="max-h-[65vh] space-y-4 overflow-y-auto pr-1">
          {/* Connection */}
          <section className="space-y-2">
            <h3 className="text-xs font-semibold text-muted-foreground">{t('settings.section.connection')}</h3>
            <FieldRow label={t('modal.settings.backendUrl')}>
              <Input
                id="set-url"
                type="text"
                value={settings.serverUrl}
                placeholder="http://127.0.0.1:8000"
                onChange={(e) => onTextChange(fields[0] as Field & { kind: 'text' }, e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && (e.target as HTMLInputElement).blur()}
              />
            </FieldRow>
          </section>

          <Separator />

          {/* Rendering */}
          <section className="space-y-2">
            <h3 className="text-xs font-semibold text-muted-foreground">{t('settings.section.rendering')}</h3>
            <FieldRow label={t('modal.settings.style')}>
              <Select value={settings.style} onValueChange={(v) => onSelectChange(fields[1] as Field, v)}>
                <SelectTrigger className="w-48">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  {(fields[1] as Field & { kind: 'select' }).options.map((o) => (
                    <SelectItem key={o.value} value={o.value}>
                      {t(o.labelKey)}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
            </FieldRow>
            <FieldRow label={t('modal.settings.opacity')}>
              <div className="flex items-center gap-3">
                <Slider
                  id="set-opacity"
                  value={[settings.opacity]}
                  min={0.05}
                  max={1}
                  step={0.05}
                  className="max-w-52"
                  onValueChange={onOpacityChange}
                />
                <span id="opacity-val" className="w-10 text-xs tabular-nums text-foreground">{opacityPct}</span>
              </div>
            </FieldRow>
          </section>

          <Separator />

          {/* Editor */}
          <section className="space-y-2">
            <h3 className="text-xs font-semibold text-muted-foreground">{t('settings.section.editor')}</h3>
            <FieldRow label={t('modal.settings.fontSize')}>
              <Input
                id="set-font-size"
                type="number"
                value={settings.fontSize}
                min={10}
                max={32}
                step="1"
                className="w-24"
                onChange={(e) => onNumberChange(fields[3] as Field & { kind: 'number' }, e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && (e.target as HTMLInputElement).blur()}
              />
            </FieldRow>
            <FieldRow label={t('modal.settings.fontFamily')}>
              <div className="flex items-center gap-2">
                <Input
                  id="set-font-family"
                  type="text"
                  value={settings.fontFamily}
                  list="font-list"
                  onChange={(e) => onTextChange(fields[4] as Field & { kind: 'text' }, e.target.value)}
                  onKeyDown={(e) => e.key === 'Enter' && (e.target as HTMLInputElement).blur()}
                />
                <datalist id="font-list">
                  {FONT_CHOICES.map((font) => (
                    <option key={font} value={font} />
                  ))}
                </datalist>
              </div>
            </FieldRow>
          </section>

          <Separator />

          {/* Colors */}
          <section className="space-y-2">
            <h3 className="text-xs font-semibold text-muted-foreground">{t('settings.section.colors')}</h3>
            <div className="grid grid-cols-[110px_1fr] items-start gap-3">
              <Label className="mt-1 text-right text-xs text-muted-foreground">
                {t('modal.settings.stops')}
                <p className="mt-0.5 font-normal normal-case leading-4">{t('modal.settings.stopsHint')}</p>
              </Label>
              <ColorStopsEditor />
            </div>
          </section>
        </div>

        <DialogFooter className="gap-2">
          <Button id="stops-reset" variant="outline" onClick={resetStops}>
            {t('modal.settings.resetStops')}
          </Button>
          <Button variant="secondary" onClick={closeModal}>{t('modal.close')}</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  )
}

function FieldRow({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="grid grid-cols-[110px_1fr] items-center gap-3">
      <Label className="text-right text-xs text-muted-foreground">{label}</Label>
      {children}
    </div>
  )
}

// editor/src/components/dialogs/SettingsDialog.vue
<script setup lang="ts">
// ---------- Settings dialog ----------
// Organized into sections; every field is one row in the DECLARATIVE `fields`
// array below (a future setting = one more row, no ad-hoc markup). Each row
// knows how to render its control, which settings key it mutates, and which
// refresh callback to fire (settings / font / server), exactly mirroring the
// historical change handlers.
import { computed } from 'vue'
import { useI18n } from '../../i18n.ts'
import { settings, saveSettings } from '../../composables/useSettings.ts'
import { useApp } from '../../composables/useApp.ts'
import { clamp } from '../../util.ts'
import type { HeatStyle } from '../../types.ts'
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from '../ui/dialog'
import { Button } from '../ui/button'
import { Label } from '../ui/label'
import { Input } from '../ui/input'
import {
  Select, SelectTrigger, SelectValue, SelectContent, SelectItem
} from '../ui/select'
import { Slider } from '../ui/slider'
import { Separator } from '../ui/separator'
import ColorStopsEditor from '../ui/ColorStopsEditor.vue'
import type { MessageKey } from '../../i18n.ts'

const { t } = useI18n()
const { settingsChanged, fontChanged, serverChanged, closeModal } = useApp()

const opacityPct = computed(() => String(Math.round(settings.opacity * 100)) + '%')

interface FieldBase {
  labelKey: MessageKey
  listId?: string
  commit: () => void
}

type Field =
  | (FieldBase & { kind: 'text'; key: 'serverUrl' | 'fontFamily' })
  | (FieldBase & { kind: 'select'; key: 'style'; options: Array<{ value: HeatStyle; labelKey: MessageKey }> })
  | (FieldBase & { kind: 'slider'; key: 'opacity'; display: () => string })
  | (FieldBase & { kind: 'number'; key: 'fontSize'; min: number; max: number })

const fields: Field[] = [
  {
    kind: 'text', key: 'serverUrl', labelKey: 'modal.settings.backendUrl',
    commit: () => serverChanged()
  },
  {
    kind: 'select', key: 'style', labelKey: 'modal.settings.style',
    options: [
      { value: 'background', labelKey: 'modal.settings.styleBackground' },
      { value: 'underline', labelKey: 'modal.settings.styleUnderline' },
      { value: 'both', labelKey: 'modal.settings.styleBoth' }
    ],
    commit: () => settingsChanged()
  },
  {
    kind: 'slider', key: 'opacity', labelKey: 'modal.settings.opacity',
    display: () => opacityPct.value,
    commit: () => settingsChanged()
  },
  {
    kind: 'number', key: 'fontSize', labelKey: 'modal.settings.fontSize', min: 10, max: 32,
    commit: () => fontChanged()
  },
  {
    kind: 'text', key: 'fontFamily', labelKey: 'modal.settings.fontFamily', listId: 'font-list',
    commit: () => fontChanged()
  }
]

/** Persist a bound value read back from a native event target. */
function commitNative(field: Field, event: Event): void {
  const target = event.target as HTMLInputElement
  if (field.kind === 'number') {
    settings.fontSize = clamp(Number(target.value) || 16, field.min, field.max)
  } else if (field.kind === 'text') {
    const v = target.value.trim()
    if (!v) return
    if (field.key === 'serverUrl') settings.serverUrl = v
    else settings.fontFamily = v
  } else {
    return
  }
  saveSettings()
  field.commit()
}

function onSelectChange(field: Field, value: unknown): void {
  if (field.kind !== 'select' || typeof value !== 'string') return
  settings.style = value as HeatStyle
  saveSettings()
  field.commit()
}

function onOpacityChange(value: number[] | undefined): void {
  settings.opacity = clamp(value?.[0] ?? settings.opacity, 0.05, 1)
  saveSettings()
  settingsChanged()
}

const FONT_CHOICES = [
  "'Segoe UI', 'Microsoft YaHei', system-ui, sans-serif",
  "'Microsoft YaHei', sans-serif",
  'SimSun, serif',
  'KaiTi, serif',
  "Consolas, 'Courier New', monospace",
  'Georgia, serif'
]

function onStopChange(): void {
  saveSettings()
  settingsChanged()
}

function resetStops(): void {
  settings.stops = [
    { ppl: 12, color: '#22c55e' },
    { ppl: 18, color: '#eab308' },
    { ppl: 50, color: '#ef4444' },
    { ppl: 100, color: '#7f1d1d' }
  ]
  saveSettings()
  settingsChanged()
}
</script>

<template>
  <Dialog :open="true" @update:open="(o) => !o && closeModal()">
    <DialogContent class="sm:max-w-2xl">
      <DialogHeader>
        <DialogTitle>{{ t('modal.settings.title') }}</DialogTitle>
        <DialogDescription>{{ t('modal.settings.hint') }}</DialogDescription>
      </DialogHeader>

      <div class="max-h-[65vh] space-y-4 overflow-y-auto pr-1">
        <!-- Connection -->
        <section class="space-y-2">
          <h3 class="text-xs font-semibold text-muted-foreground">{{ t('settings.section.connection') }}</h3>
          <template v-for="f in fields.filter((f) => f.key === 'serverUrl')" :key="f.key">
            <div class="grid grid-cols-[110px_1fr] items-center gap-3">
              <Label class="text-right text-xs text-muted-foreground">{{ t(f.labelKey) }}</Label>
              <Input
                id="set-url"
                type="text"
                :model-value="settings.serverUrl"
                placeholder="http://127.0.0.1:8000"
                @change="commitNative(f, $event)"
                @keydown.enter="(e: KeyboardEvent) => (e.target as HTMLInputElement).blur()"
              />
            </div>
          </template>
        </section>

        <Separator />

        <!-- Rendering -->
        <section class="space-y-2">
          <h3 class="text-xs font-semibold text-muted-foreground">{{ t('settings.section.rendering') }}</h3>
          <template v-for="f in fields.filter((f2) => f2.key === 'style' || f2.key === 'opacity')" :key="f.key">
            <div class="grid grid-cols-[110px_1fr] items-center gap-3">
              <Label class="text-right text-xs text-muted-foreground">{{ t(f.labelKey) }}</Label>
              <template v-if="f.kind === 'select'">
                <Select :model-value="settings.style" @update:model-value="(v) => onSelectChange(f, v)">
                  <SelectTrigger class="w-48">
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem v-for="o in f.options" :key="o.value" :value="o.value">
                      {{ t(o.labelKey) }}
                    </SelectItem>
                  </SelectContent>
                </Select>
              </template>
              <template v-else-if="f.kind === 'slider'">
                <div class="flex items-center gap-3">
                  <Slider
                    id="set-opacity"
                    :model-value="[settings.opacity]"
                    :min="0.05"
                    :max="1"
                    :step="0.05"
                    class="max-w-52"
                    @update:model-value="onOpacityChange"
                  />
                  <span id="opacity-val" class="w-10 text-xs tabular-nums text-foreground">{{ f.display() }}</span>
                </div>
              </template>
            </div>
          </template>
        </section>

        <Separator />

        <!-- Editor -->
        <section class="space-y-2">
          <h3 class="text-xs font-semibold text-muted-foreground">{{ t('settings.section.editor') }}</h3>
          <template v-for="f in fields.filter((x): x is typeof x => x.key === 'fontSize' || x.key === 'fontFamily')" :key="f.key">
            <div class="grid grid-cols-[110px_1fr] items-center gap-3">
              <Label class="text-right text-xs text-muted-foreground">{{ t(f.labelKey) }}</Label>
              <template v-if="f.kind === 'number'">
                <Input
                  id="set-font-size"
                  type="number"
                  :model-value="settings.fontSize"
                  :min="f.min"
                  :max="f.max"
                  step="1"
                  class="w-24"
                  @change="commitNative(f, $event)"
                  @keydown.enter="(e: KeyboardEvent) => (e.target as HTMLInputElement).blur()"
                />
              </template>
              <template v-else>
                <div class="flex items-center gap-2">
                  <Input
                    id="set-font-family"
                    type="text"
                    :model-value="settings.fontFamily"
                    :list="f.listId"
                    @change="commitNative(f, $event)"
                    @keydown.enter="(e: KeyboardEvent) => (e.target as HTMLInputElement).blur()"
                  />
                  <datalist id="font-list">
                    <option v-for="font in FONT_CHOICES" :key="font" :value="font"></option>
                  </datalist>
                </div>
              </template>
            </div>
          </template>
        </section>

        <Separator />

        <!-- Colors -->
        <section class="space-y-2">
          <h3 class="text-xs font-semibold text-muted-foreground">{{ t('settings.section.colors') }}</h3>
          <div class="grid grid-cols-[110px_1fr] items-start gap-3">
            <Label class="mt-1 text-right text-xs text-muted-foreground">
              {{ t('modal.settings.stops') }}
              <p class="mt-0.5 font-normal normal-case leading-4">{{ t('modal.settings.stopsHint') }}</p>
            </Label>
            <ColorStopsEditor @change="onStopChange" />
          </div>
        </section>
      </div>

      <DialogFooter class="gap-2">
        <Button id="stops-reset" variant="outline" @click="resetStops">{{ t('modal.settings.resetStops') }}</Button>
        <Button variant="secondary" @click="closeModal">{{ t('modal.close') }}</Button>
      </DialogFooter>
    </DialogContent>
  </Dialog>
</template>
