// editor/src/components/ui/ColorStopsEditor.tsx
// ---------- Color-stop editor ----------
// ppl + color rows for the settings dialog. Mutates the settings store (copied
// arrays), which is persisted and re-renders the heat map immediately.
import { Plus, Trash2 } from 'lucide-react'
import { useI18n } from '@/i18n.ts'
import { useSettingsStore } from '@/stores/settings.ts'
import { toast } from '@/composables/useToasts.ts'
import { Button } from './button'
import { Input } from './input'
import type { ColorStop } from '@/types.ts'

export function ColorStopsEditor() {
  const stops = useSettingsStore((s) => s.settings.stops)
  const { t } = useI18n()

  function patchStops(next: ColorStop[]): void {
    useSettingsStore.getState().patchSettings({ stops: next })
  }

  function onPplChange(index: number, value: string): void {
    const next = stops.map((s) => ({ ...s }))
    next[index]!.ppl = Math.max(0, Number(value) || 0)
    next.sort((a, b) => a.ppl - b.ppl)
    patchStops(next)
  }

  function onColorChange(index: number, value: string): void {
    const next = stops.map((s) => ({ ...s }))
    next[index]!.color = value
    patchStops(next)
  }

  function onDelete(index: number): void {
    if (stops.length <= 1) {
      toast(t('toast.minStops'), 'warn')
      return
    }
    const next = stops.filter((_, i) => i !== index)
    patchStops(next)
  }

  function onAdd(): void {
    const last = stops[stops.length - 1]
    patchStops([...stops.map((s) => ({ ...s })), { ppl: (last ? last.ppl : 10) * 2, color: '#ef4444' }])
  }

  return (
    <div className="space-y-1.5">
      {stops.map((s, i) => (
        <div key={`${i}-${s.ppl}`} className="stop-row flex items-center gap-2 rounded-md border px-2 py-1.5">
          <span className="shrink-0 text-[11px] text-muted-foreground">{t('modal.settings.stopPpl')}</span>
          <Input
            type="number"
            value={s.ppl}
            min="0"
            step="0.01"
            className="h-7 w-20 text-sm"
            onChange={(e) => onPplChange(i, e.target.value)}
          />
          <span
            className="h-7 w-8 shrink-0 cursor-pointer overflow-hidden rounded-md border"
            style={{ backgroundColor: s.color }}
            title={s.color}
          >
            <input
              type="color"
              className="size-full cursor-pointer opacity-0"
              value={s.color}
              onChange={(e) => onColorChange(i, e.target.value)}
            />
          </span>
          <span className="flex-1 truncate font-mono text-[11px] text-muted-foreground">{s.color}</span>
          <Button size="icon-xs" variant="ghost" title={t('modal.settings.stopDeleteHint')} onClick={() => onDelete(i)}>
            <Trash2 className="size-3 text-muted-foreground" />
          </Button>
        </div>
      ))}
      <Button id="stop-add" variant="outline" size="sm" className="w-full" onClick={onAdd}>
        <Plus className="size-3.5" />
        {t('modal.settings.stopAdd')}
      </Button>
    </div>
  )
}

// editor/src/components/ui/ColorStopsEditor.vue
<script setup lang="ts">
// ---------- Color-stop editor ----------
// ppl + color rows for the settings dialog. Mutates the shared reactive settings;
// the parent is notified via `change` so decorations and stats refresh.
import { Plus, Trash2 } from '@lucide/vue'
import { useI18n } from '../../i18n.ts'
import { settings } from '../../composables/useSettings.ts'
import { toast } from '../../composables/useToasts.ts'
import { Button } from './button'
import { Input } from './input'

const emit = defineEmits<{ change: [] }>()

const { t } = useI18n()

function notifyChange(): void {
  emit('change')
}

function onPplChange(index: number, value: string): void {
  settings.stops[index].ppl = Math.max(0, Number(value) || 0)
  settings.stops.sort((a, b) => a.ppl - b.ppl)
  notifyChange()
}

function onColorChange(index: number, value: string): void {
  settings.stops[index].color = value
  notifyChange()
}

function onDelete(index: number): void {
  if (settings.stops.length <= 1) {
    toast(t('toast.minStops'), 'warn')
    return
  }
  settings.stops.splice(index, 1)
  notifyChange()
}

function onAdd(): void {
  const last = settings.stops[settings.stops.length - 1]
  settings.stops.push({ ppl: (last ? last.ppl : 10) * 2, color: '#ef4444' })
  notifyChange()
}
</script>

<template>
  <div class="space-y-1.5">
    <div
      v-for="(s, i) in settings.stops"
      :key="`${i}-${s.ppl}`"
      class="stop-row flex items-center gap-2 rounded-md border px-2 py-1.5"
    >
      <span class="shrink-0 text-[11px] text-muted-foreground">{{ t('modal.settings.stopPpl') }}</span>
      <Input
        type="number"
        :model-value="s.ppl"
        min="0"
        step="0.01"
        class="h-7 w-20 text-sm"
        @update:model-value="onPplChange(i, String($event))"
      />
      <span
        class="h-7 w-8 shrink-0 cursor-pointer overflow-hidden rounded-md border"
        :style="{ backgroundColor: s.color }"
        :title="s.color"
      >
        <input
          type="color"
          class="size-full cursor-pointer opacity-0"
          :value="s.color"
          @input="onColorChange(i, ($event.target as HTMLInputElement).value)"
        />
      </span>
      <span class="flex-1 truncate font-mono text-[11px] text-muted-foreground">{{ s.color }}</span>
      <Button size="icon-xs" variant="ghost" :title="t('modal.settings.stopDeleteHint')" @click="onDelete(i)">
        <Trash2 class="size-3 text-muted-foreground" />
      </Button>
    </div>
    <Button id="stop-add" variant="outline" size="sm" class="w-full" @click="onAdd">
      <Plus class="size-3.5" />
      {{ t('modal.settings.stopAdd') }}
    </Button>
  </div>
</template>
